apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: landmund/fastapi:20231120
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
      - name: db
        image: landmund/postgres:20231120
        ports:
          - containerPort: 5432
            name: "postgres"
        env:
          - name: POSTGRES_DB
            value: "alzheimer_predict"
          - name: POSTGRES_USER
            value: "alzheimer_predict_user"
          - name: POSTGRES_PASSWORD
            value: "12345678"
        resources:
          limits:
            memory: 4Gi
            cpu: "2"