apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - name: ingress
      port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-ui-service
spec:
  selector:
    app: nodejs
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer